2017-02-23 16:15:16,304 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-23 16:15:16,540 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-23 16:15:16,931 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-23 16:15:16,977 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-23 16:15:17,030 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-23 16:15:17,069 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-23 16:15:17,089 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-23 16:15:17,091 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-23 16:15:17,091 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 13:50:35,069 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 13:50:35,069 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 13:50:35,086 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 13:50:35,099 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 13:50:35,280 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 13:50:35,289 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 13:50:35,312 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 13:50:35,323 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 13:50:35,336 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:19:58,469 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:19:58,774 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:19:58,837 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:19:58,966 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:19:58,991 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:19:59,055 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:19:59,057 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:19:59,077 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:19:59,077 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:39:22,658 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:39:22,991 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:39:23,187 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:39:23,214 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:39:23,224 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:39:23,260 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:39:23,266 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:39:23,286 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:39:23,305 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:48:27,941 Exception on /check [GET]
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 665, in regularpage
    return render_template(pagename)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: check
2017-02-24 15:39:23,935 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 15:39:24,036 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 15:39:24,398 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 15:39:24,422 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 15:39:24,441 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 15:39:24,456 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 15:39:24,467 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 15:39:24,489 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 15:39:24,513 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2017-02-24 16:15:25 -0500] [95623] [CRITICAL] WORKER TIMEOUT (pid:95627)
[2017-02-24 16:15:25 -0500] [95623] [CRITICAL] WORKER TIMEOUT (pid:95628)
[2017-02-24 16:15:25 -0500] [95623] [CRITICAL] WORKER TIMEOUT (pid:95629)
[2017-02-24 16:15:25 -0500] [95623] [CRITICAL] WORKER TIMEOUT (pid:95630)
[2017-02-24 16:15:25 -0500] [95623] [CRITICAL] WORKER TIMEOUT (pid:95631)
[2017-02-24 16:15:25 -0500] [95623] [CRITICAL] WORKER TIMEOUT (pid:95632)
[2017-02-24 16:15:25 -0500] [95623] [CRITICAL] WORKER TIMEOUT (pid:95633)
[2017-02-24 16:15:25 -0500] [95623] [CRITICAL] WORKER TIMEOUT (pid:95634)
[2017-02-24 16:15:25 -0500] [95623] [CRITICAL] WORKER TIMEOUT (pid:95635)
2017-02-24 16:15:29,671 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 16:15:29,695 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 16:15:29,786 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 16:15:29,814 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 16:15:29,815 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 16:15:29,822 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 16:15:29,839 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 16:15:29,839 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 16:15:29,926 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2017-02-24 16:53:02 +0000] [8875] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:53:02 +0000] [8876] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:53:02 +0000] [8877] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:53:02 +0000] [8879] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:53:02 +0000] [8878] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:14 +0000] [2166] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:14 +0000] [2167] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:14 +0000] [2169] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:14 +0000] [2168] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:14 +0000] [2170] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:26 +0000] [2220] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:26 +0000] [2221] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:26 +0000] [2224] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:26 +0000] [2223] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:26 +0000] [2222] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:53 +0000] [2332] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:54 +0000] [2333] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:54 +0000] [2334] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:54 +0000] [2335] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:54 +0000] [2336] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 17:01:18 +0000] [2503] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 17:01:18 +0000] [2501] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 17:01:18 +0000] [2502] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 17:01:18 +0000] [2505] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 17:01:18 +0000] [2504] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-26 11:56:14 -0500] [1497] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
[2017-02-26 11:56:14 -0500] [1496] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
[2017-02-26 11:56:15 -0500] [1498] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
[2017-02-26 11:56:15 -0500] [1499] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
[2017-02-26 11:56:15 -0500] [1500] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
[2017-02-26 11:56:15 -0500] [1501] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
[2017-02-26 11:56:15 -0500] [1502] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
[2017-02-26 11:56:15 -0500] [1503] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
[2017-02-26 11:56:15 -0500] [1504] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
2017-02-26 11:57:45,812 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-26 11:57:45,838 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-26 11:57:45,986 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-26 11:57:46,054 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-26 11:57:46,097 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-26 11:57:46,101 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-26 11:57:46,104 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-26 11:57:46,124 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-26 11:57:46,137 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:15,284 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:15,284 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:15,331 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:15,401 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:15,438 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:15,466 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:15,491 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:15,495 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:15,511 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:27,643 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:27,801 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:27,849 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:27,884 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:27,920 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:27,962 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:27,970 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:27,981 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:27,988 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-05-25 14:31:36,136 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-05-25 14:31:36,398 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-05-25 14:31:36,580 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-05-25 14:31:36,688 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-05-25 14:31:36,695 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-05-25 14:31:36,707 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-05-25 14:31:36,717 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-05-25 14:31:36,721 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-05-25 14:31:36,726 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2017-05-25 16:37:54 -0400] [598] [CRITICAL] WORKER TIMEOUT (pid:608)
[2017-05-25 16:37:54 -0400] [598] [CRITICAL] WORKER TIMEOUT (pid:609)
[2017-05-25 16:37:54 -0400] [598] [CRITICAL] WORKER TIMEOUT (pid:610)
[2017-05-25 16:37:54 -0400] [598] [CRITICAL] WORKER TIMEOUT (pid:602)
[2017-05-25 16:37:54 -0400] [598] [CRITICAL] WORKER TIMEOUT (pid:603)
[2017-05-25 16:37:54 -0400] [598] [CRITICAL] WORKER TIMEOUT (pid:604)
[2017-05-25 16:37:54 -0400] [598] [CRITICAL] WORKER TIMEOUT (pid:605)
[2017-05-25 16:37:54 -0400] [598] [CRITICAL] WORKER TIMEOUT (pid:606)
[2017-05-25 16:37:54 -0400] [598] [CRITICAL] WORKER TIMEOUT (pid:607)
[2017-05-31 11:30:31 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:16337)
[2017-05-31 11:30:31 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:16338)
[2017-05-31 11:30:31 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:16339)
[2017-05-31 11:30:31 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:16340)
[2017-05-31 11:30:31 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:16341)
[2017-05-31 11:30:31 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:16342)
[2017-05-31 11:30:31 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:16343)
[2017-05-31 11:30:31 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:16344)
[2017-05-31 11:30:31 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:16345)
[2017-05-31 12:59:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:17386)
[2017-05-31 12:59:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:17387)
[2017-05-31 12:59:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:17388)
[2017-05-31 12:59:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:17389)
[2017-05-31 12:59:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:17390)
[2017-05-31 12:59:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:17391)
[2017-05-31 12:59:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:17392)
[2017-05-31 12:59:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:17393)
[2017-05-31 12:59:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:17394)
[2017-05-31 13:59:46 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18336)
[2017-05-31 13:59:46 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18337)
[2017-05-31 13:59:46 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18329)
[2017-05-31 13:59:46 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18330)
[2017-05-31 13:59:46 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18331)
[2017-05-31 13:59:46 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18332)
[2017-05-31 13:59:46 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18333)
[2017-05-31 13:59:46 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18334)
[2017-05-31 13:59:46 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18335)
[2017-05-31 15:00:32 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18369)
[2017-05-31 15:00:32 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18371)
[2017-05-31 15:00:32 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18372)
[2017-05-31 15:00:32 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18373)
[2017-05-31 15:00:32 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18374)
[2017-05-31 15:00:32 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18375)
[2017-05-31 15:00:32 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18376)
[2017-05-31 15:00:32 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18377)
[2017-05-31 15:00:32 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18378)
[2017-05-31 15:27:32 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18412)
[2017-05-31 15:27:32 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18413)
[2017-05-31 15:27:32 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18414)
[2017-05-31 15:27:32 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18415)
[2017-05-31 15:27:32 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18416)
[2017-05-31 15:27:32 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18417)
[2017-05-31 15:27:32 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18418)
[2017-05-31 15:27:32 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18419)
[2017-05-31 15:27:32 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18420)
[2017-05-31 16:49:36 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18450)
[2017-05-31 16:49:36 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18451)
[2017-05-31 16:49:36 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18452)
[2017-05-31 16:49:36 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18453)
[2017-05-31 16:49:36 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18454)
[2017-05-31 16:49:36 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18455)
[2017-05-31 16:49:36 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18456)
[2017-05-31 16:49:36 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18458)
[2017-05-31 16:49:36 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:18459)
[2017-05-31 17:22:48 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:19761)
[2017-05-31 17:22:48 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:19762)
[2017-05-31 17:22:48 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:19763)
[2017-05-31 17:22:48 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:19764)
[2017-05-31 17:22:48 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:19765)
[2017-05-31 17:22:48 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:19767)
[2017-05-31 17:22:48 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:19768)
[2017-05-31 17:22:48 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:19769)
[2017-05-31 17:22:48 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:19770)
[2017-05-31 20:25:27 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:20087)
[2017-05-31 21:03:05 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:25676)
[2017-05-31 21:03:05 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:20088)
[2017-05-31 21:03:05 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:20086)
[2017-05-31 21:03:05 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:20089)
[2017-05-31 21:03:05 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:20090)
[2017-05-31 21:03:05 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:20091)
[2017-05-31 21:03:05 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:20092)
[2017-05-31 21:03:05 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:20093)
[2017-05-31 21:03:05 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:20085)
[2017-05-31 21:37:01 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:25710)
[2017-05-31 21:37:01 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:25711)
[2017-05-31 21:37:01 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:25712)
[2017-05-31 21:37:01 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:25713)
[2017-05-31 21:37:01 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:25714)
[2017-05-31 21:37:01 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:25715)
[2017-05-31 21:37:01 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:25716)
[2017-05-31 21:37:01 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:25717)
[2017-05-31 21:37:01 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:25718)
[2017-05-31 22:39:56 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26064)
[2017-05-31 22:39:56 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26065)
[2017-05-31 22:39:56 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26066)
[2017-05-31 22:39:56 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26067)
[2017-05-31 22:39:56 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26068)
[2017-05-31 22:39:56 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26069)
[2017-05-31 22:39:56 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26070)
[2017-05-31 22:39:56 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26071)
[2017-05-31 22:39:56 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26072)
[2017-05-31 23:54:58 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26415)
[2017-05-31 23:54:58 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26416)
[2017-05-31 23:54:58 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26417)
[2017-05-31 23:54:58 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26418)
[2017-05-31 23:54:58 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26419)
[2017-05-31 23:54:58 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26420)
[2017-05-31 23:54:58 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26421)
[2017-05-31 23:54:58 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26422)
[2017-05-31 23:54:58 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26423)
[2017-06-01 00:55:43 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26919)
[2017-06-01 00:55:43 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26920)
[2017-06-01 00:55:43 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26921)
[2017-06-01 00:55:43 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26922)
[2017-06-01 00:55:43 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26923)
[2017-06-01 00:55:43 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26924)
[2017-06-01 00:55:43 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26925)
[2017-06-01 00:55:43 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26926)
[2017-06-01 00:55:43 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26927)
[2017-06-01 01:56:28 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26959)
[2017-06-01 01:56:28 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26960)
[2017-06-01 01:56:28 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26961)
[2017-06-01 01:56:28 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26962)
[2017-06-01 01:56:28 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26963)
[2017-06-01 01:56:28 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26964)
[2017-06-01 01:56:28 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26965)
[2017-06-01 01:56:28 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26966)
[2017-06-01 01:56:28 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26967)
[2017-06-01 02:57:13 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26997)
[2017-06-01 02:57:13 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26998)
[2017-06-01 02:57:13 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:26999)
[2017-06-01 02:57:13 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27000)
[2017-06-01 02:57:13 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27001)
[2017-06-01 02:57:13 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27002)
[2017-06-01 02:57:13 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27003)
[2017-06-01 02:57:13 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27004)
[2017-06-01 02:57:13 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27005)
[2017-06-01 03:57:58 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27044)
[2017-06-01 03:57:58 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27045)
[2017-06-01 03:57:58 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27046)
[2017-06-01 03:57:58 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27048)
[2017-06-01 03:57:58 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27049)
[2017-06-01 03:57:58 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27050)
[2017-06-01 03:57:58 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27051)
[2017-06-01 03:57:58 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27052)
[2017-06-01 03:57:58 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27053)
[2017-06-01 04:59:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27104)
[2017-06-01 04:59:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27106)
[2017-06-01 04:59:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27107)
[2017-06-01 04:59:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27108)
[2017-06-01 04:59:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27097)
[2017-06-01 04:59:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27099)
[2017-06-01 04:59:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27100)
[2017-06-01 04:59:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27102)
[2017-06-01 04:59:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27103)
[2017-06-01 05:59:45 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27176)
[2017-06-01 05:59:45 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27177)
[2017-06-01 05:59:45 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27178)
[2017-06-01 05:59:45 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27179)
[2017-06-01 05:59:45 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27180)
[2017-06-01 05:59:45 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27181)
[2017-06-01 05:59:45 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27182)
[2017-06-01 05:59:45 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27183)
[2017-06-01 05:59:45 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27184)
[2017-06-01 07:00:30 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27218)
[2017-06-01 07:00:30 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27219)
[2017-06-01 07:00:30 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27220)
[2017-06-01 07:00:30 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27221)
[2017-06-01 07:00:30 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27222)
[2017-06-01 07:00:30 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27223)
[2017-06-01 07:00:30 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27224)
[2017-06-01 07:00:30 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27225)
[2017-06-01 07:00:30 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27226)
[2017-06-01 08:01:15 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27264)
[2017-06-01 08:01:15 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27265)
[2017-06-01 08:01:15 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27256)
[2017-06-01 08:01:15 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27257)
[2017-06-01 08:01:15 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27258)
[2017-06-01 08:01:15 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27259)
[2017-06-01 08:01:15 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27260)
[2017-06-01 08:01:15 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27261)
[2017-06-01 08:01:15 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27262)
[2017-06-01 09:02:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27296)
[2017-06-01 09:02:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27297)
[2017-06-01 09:02:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27298)
[2017-06-01 09:02:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27299)
[2017-06-01 09:02:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27300)
[2017-06-01 09:02:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27301)
[2017-06-01 09:02:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27302)
[2017-06-01 09:02:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27303)
[2017-06-01 09:02:00 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27304)
[2017-06-01 09:21:30 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27342)
[2017-06-01 09:21:30 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27343)
[2017-06-01 09:21:30 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27344)
[2017-06-01 09:21:30 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27345)
[2017-06-01 09:21:30 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27346)
[2017-06-01 09:21:30 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27347)
[2017-06-01 09:21:30 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27348)
[2017-06-01 09:21:30 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27349)
[2017-06-01 09:21:30 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27350)
[2017-06-01 09:49:44 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27392)
[2017-06-01 09:49:44 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27384)
[2017-06-01 09:49:44 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27385)
[2017-06-01 09:49:44 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27386)
[2017-06-01 09:49:44 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27387)
[2017-06-01 09:49:44 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27388)
[2017-06-01 09:49:44 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27389)
[2017-06-01 09:49:44 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27390)
[2017-06-01 09:49:44 -0400] [16333] [CRITICAL] WORKER TIMEOUT (pid:27391)
[2017-06-22 14:20:27 -0400] [5923] [CRITICAL] WORKER TIMEOUT (pid:5927)
[2017-06-22 14:20:27 -0400] [5923] [CRITICAL] WORKER TIMEOUT (pid:5928)
[2017-06-22 14:20:27 -0400] [5923] [CRITICAL] WORKER TIMEOUT (pid:5929)
[2017-06-22 14:20:27 -0400] [5923] [CRITICAL] WORKER TIMEOUT (pid:5930)
[2017-06-22 14:20:27 -0400] [5923] [CRITICAL] WORKER TIMEOUT (pid:5931)
[2017-06-22 14:20:27 -0400] [5923] [CRITICAL] WORKER TIMEOUT (pid:5932)
[2017-06-22 14:20:27 -0400] [5923] [CRITICAL] WORKER TIMEOUT (pid:5933)
[2017-06-22 14:20:27 -0400] [5923] [CRITICAL] WORKER TIMEOUT (pid:5934)
[2017-06-22 14:20:27 -0400] [5923] [CRITICAL] WORKER TIMEOUT (pid:5935)
[2017-06-22 14:50:43 -0400] [5923] [CRITICAL] WORKER TIMEOUT (pid:9266)
[2017-06-22 14:50:43 -0400] [5923] [CRITICAL] WORKER TIMEOUT (pid:9267)
[2017-06-22 14:50:43 -0400] [5923] [CRITICAL] WORKER TIMEOUT (pid:9268)
[2017-06-22 14:50:43 -0400] [5923] [CRITICAL] WORKER TIMEOUT (pid:9269)
[2017-06-22 14:50:43 -0400] [5923] [CRITICAL] WORKER TIMEOUT (pid:9270)
[2017-06-22 14:50:43 -0400] [5923] [CRITICAL] WORKER TIMEOUT (pid:9271)
[2017-06-22 14:50:43 -0400] [5923] [CRITICAL] WORKER TIMEOUT (pid:9272)
[2017-06-22 14:50:43 -0400] [5923] [CRITICAL] WORKER TIMEOUT (pid:9273)
[2017-06-22 14:50:43 -0400] [5923] [CRITICAL] WORKER TIMEOUT (pid:9274)
[2017-06-22 16:05:39 -0400] [5923] [CRITICAL] WORKER TIMEOUT (pid:9321)
[2017-06-22 16:05:39 -0400] [5923] [CRITICAL] WORKER TIMEOUT (pid:9324)
[2017-06-22 16:05:39 -0400] [5923] [CRITICAL] WORKER TIMEOUT (pid:9325)
[2017-06-22 16:05:39 -0400] [5923] [CRITICAL] WORKER TIMEOUT (pid:9327)
[2017-06-30 12:27:09 -0400] [5668] [CRITICAL] WORKER TIMEOUT (pid:5672)
[2017-06-30 12:27:09 -0400] [5668] [CRITICAL] WORKER TIMEOUT (pid:5673)
[2017-06-30 12:27:09 -0400] [5668] [CRITICAL] WORKER TIMEOUT (pid:5674)
[2017-06-30 12:27:09 -0400] [5668] [CRITICAL] WORKER TIMEOUT (pid:5675)
[2017-06-30 12:27:09 -0400] [5668] [CRITICAL] WORKER TIMEOUT (pid:5676)
[2017-06-30 12:27:09 -0400] [5668] [CRITICAL] WORKER TIMEOUT (pid:5677)
[2017-06-30 12:27:09 -0400] [5668] [CRITICAL] WORKER TIMEOUT (pid:5678)
[2017-06-30 12:27:09 -0400] [5668] [CRITICAL] WORKER TIMEOUT (pid:5679)
[2017-06-30 12:27:09 -0400] [5668] [CRITICAL] WORKER TIMEOUT (pid:5680)
2017-11-01 10:11:15,720 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-11-01 10:11:15,963 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-11-01 10:11:16,190 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-11-01 10:11:16,351 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-11-01 10:11:16,380 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-11-01 10:11:16,400 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-11-01 10:11:16,410 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-11-01 10:11:16,448 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-11-01 10:11:16,466 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-11-01 10:11:33,353 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-11-01 10:11:33,629 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-11-01 10:11:33,854 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-11-01 10:11:34,060 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-11-01 10:11:34,148 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-11-01 10:11:34,149 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-11-01 10:11:34,176 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-11-01 10:11:34,200 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-11-01 10:11:34,225 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
