2017-02-23 16:15:16,304 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-23 16:15:16,540 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-23 16:15:16,931 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-23 16:15:16,977 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-23 16:15:17,030 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-23 16:15:17,069 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-23 16:15:17,089 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-23 16:15:17,091 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-23 16:15:17,091 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 13:50:35,069 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 13:50:35,069 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 13:50:35,086 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 13:50:35,099 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 13:50:35,280 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 13:50:35,289 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 13:50:35,312 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 13:50:35,323 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 13:50:35,336 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:19:58,469 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:19:58,774 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:19:58,837 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:19:58,966 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:19:58,991 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:19:59,055 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:19:59,057 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:19:59,077 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:19:59,077 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:39:22,658 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:39:22,991 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:39:23,187 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:39:23,214 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:39:23,224 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:39:23,260 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:39:23,266 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:39:23,286 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:39:23,305 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 14:48:27,941 Exception on /check [GET]
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 665, in regularpage
    return render_template(pagename)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: check
2017-02-24 15:39:23,935 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 15:39:24,036 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 15:39:24,398 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 15:39:24,422 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 15:39:24,441 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 15:39:24,456 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 15:39:24,467 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 15:39:24,489 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 15:39:24,513 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2017-02-24 16:15:25 -0500] [95623] [CRITICAL] WORKER TIMEOUT (pid:95627)
[2017-02-24 16:15:25 -0500] [95623] [CRITICAL] WORKER TIMEOUT (pid:95628)
[2017-02-24 16:15:25 -0500] [95623] [CRITICAL] WORKER TIMEOUT (pid:95629)
[2017-02-24 16:15:25 -0500] [95623] [CRITICAL] WORKER TIMEOUT (pid:95630)
[2017-02-24 16:15:25 -0500] [95623] [CRITICAL] WORKER TIMEOUT (pid:95631)
[2017-02-24 16:15:25 -0500] [95623] [CRITICAL] WORKER TIMEOUT (pid:95632)
[2017-02-24 16:15:25 -0500] [95623] [CRITICAL] WORKER TIMEOUT (pid:95633)
[2017-02-24 16:15:25 -0500] [95623] [CRITICAL] WORKER TIMEOUT (pid:95634)
[2017-02-24 16:15:25 -0500] [95623] [CRITICAL] WORKER TIMEOUT (pid:95635)
2017-02-24 16:15:29,671 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 16:15:29,695 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 16:15:29,786 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 16:15:29,814 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 16:15:29,815 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 16:15:29,822 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 16:15:29,839 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 16:15:29,839 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-24 16:15:29,926 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2017-02-24 16:53:02 +0000] [8875] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:53:02 +0000] [8876] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:53:02 +0000] [8877] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:53:02 +0000] [8879] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:53:02 +0000] [8878] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:14 +0000] [2166] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:14 +0000] [2167] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:14 +0000] [2169] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:14 +0000] [2168] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:14 +0000] [2170] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:26 +0000] [2220] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:26 +0000] [2221] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:26 +0000] [2224] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:26 +0000] [2223] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:26 +0000] [2222] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:53 +0000] [2332] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:54 +0000] [2333] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:54 +0000] [2334] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:54 +0000] [2335] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 16:56:54 +0000] [2336] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 17:01:18 +0000] [2503] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 17:01:18 +0000] [2501] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 17:01:18 +0000] [2502] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 17:01:18 +0000] [2505] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-24 17:01:18 +0000] [2504] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.1.2-py2.7.egg/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/mnt/ski/home/franklin/GoalTask_3Goals_exp4b/custom.py", line 96
    try:
       ^
IndentationError: unindent does not match any outer indentation level
[2017-02-26 11:56:14 -0500] [1497] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
[2017-02-26 11:56:14 -0500] [1496] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
[2017-02-26 11:56:15 -0500] [1498] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
[2017-02-26 11:56:15 -0500] [1499] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
[2017-02-26 11:56:15 -0500] [1500] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
[2017-02-26 11:56:15 -0500] [1501] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
[2017-02-26 11:56:15 -0500] [1502] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
[2017-02-26 11:56:15 -0500] [1503] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
[2017-02-26 11:56:15 -0500] [1504] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
Traceback (most recent call last):
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 82, in <module>
    app.register_blueprint(custom_code)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/werkzeug/routing.py", line 599, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
2017-02-26 11:57:45,812 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-26 11:57:45,838 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-26 11:57:45,986 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-26 11:57:46,054 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-26 11:57:46,097 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-26 11:57:46,101 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-26 11:57:46,104 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-26 11:57:46,124 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-02-26 11:57:46,137 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:15,284 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:15,284 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:15,331 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:15,401 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:15,438 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:15,466 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:15,491 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:15,495 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:15,511 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:27,643 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:27,801 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:27,849 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:27,884 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:27,920 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:27,962 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:27,970 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:27,981 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2017-04-11 14:55:27,988 /Users/nickfranklin/anaconda/envs/run-psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
